version: '3'

services:
  learning_center-database : 
    image: postgres:latest 
    container_name: learning_center-database  
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - learning_center-network

  web-project:
    hostname: "${HOSTNAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/platform
    command: [
        "sh",
        "-c", 
        "pip install debugpy -t /tmp && 
        python /tmp/debugpy --wait-for-client --listen 0.0.0.0:3000
        ./manage.py runserver ${HOSTNAME}:${PORT}"
    ]
    volumes:
      - ./platform/:/usr/src/platform
    ports:
      - "${PORT}:${PORT}"
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
    env_file:
      .env
    depends_on:
      - learning_center-database 
    networks:
      - learning_center-network

networks:
    learning_center-network:
        external: true
