# Generated by Django 4.2.16 on 2025-08-12 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('native_language', models.CharField(choices=[('portuguese', 'Portuguese'), ('english', 'English'), ('other', 'Other')], max_length=50)),
                ('portuguese_level', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], max_length=20)),
                ('english_level', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], max_length=20)),
                ('field_of_expertise', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('resume_file', models.FileField(upload_to='curriculos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
