# Generated by Django 4.2.16 on 2025-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM')], max_length=10)),
                ('number_of_children', models.PositiveSmallIntegerField(default=1)),
                ('children_ages', models.CharField(help_text='Example: 2, 4, 6', max_length=100)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Visit Schedule',
                'verbose_name_plural': 'Visit Schedules',
                'ordering': ['-visit_date', 'time_slot'],
            },
        ),
    ]
